## Data Frames

In [9]:
print("checking environment")

checking environment

In [10]:
import pandas as pd

df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"])

In [11]:
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
df.head(2)

   A  B  C
0  1  2  3
1  4  5  6

In [14]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [15]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [16]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"], index=["x","y","z"])
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [ ]:
df.describe() #general stats

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [20]:
df['A']

x    1
y    4
z    7
Name: A, dtype: int64